var requirejs,require,define;
(function(ga){function la(b,c,f,h){return h||""}function K(b){return"[object Function]"===R.call(b)}function L(b){return"[object Array]"===R.call(b)}function y(b,c){if(b){var f;for(f=0;f<b.length&&(!b[f]||!c(b[f],f,b));f+=1);}}function W(b,c){if(b){var f;for(f=b.length-1;-1<f&&(!b[f]||!c(b[f],f,b));--f);}}function x(b,c){return ma.call(b,c)}function p(b,c){return x(b,c)&&b[c]}function D(b,c){for(var f in b)if(x(b,f)&&c(b[f],f))break}function X(b,c,f,h){c&&D(c,function(c,p){if(f||!x(b,p))!h||"object"!==
typeof c||!c||L(c)||K(c)||c instanceof RegExp?b[p]=c:(b[p]||(b[p]={}),X(b[p],c,f,h))});return b}function z(b,c){return function(){return c.apply(b,arguments)}}function ha(b){throw b;}function ia(b){if(!b)return b;var c=ga;y(b.split("."),function(b){c=c[b]});return c}function F(b,c,f,h){c=Error(c+"\nhttp://requirejs.org/docs/errors.html#"+b);c.requireType=b;c.requireModules=h;f&&(c.originalError=f);return c}function na(b){function c(a,g,b){var e,k,d,c,f,l,h,n;g=g&&g.split("/");var r=q.map,m=r&&r["*"];
if(a){a=a.split("/");k=a.length-1;q.nodeIdCompat&&S.test(a[k])&&(a[k]=a[k].replace(S,""));"."===a[0].charAt(0)&&g&&(k=g.slice(0,g.length-1),a=k.concat(a));k=a;for(d=0;d<k.length;d++)c=k[d],"."===c?(k.splice(d,1),--d):".."===c&&0!==d&&(1!==d||".."!==k[2])&&".."!==k[d-1]&&0<d&&(k.splice(d-1,2),d-=2);a=a.join("/")}if(b&&r&&(g||m)){k=a.split("/");d=k.length;a:for(;0<d;--d){f=k.slice(0,d).join("/");if(g)for(c=g.length;0<c;--c)if(b=p(r,g.slice(0,c).join("/")))if(b=p(b,f)){e=b;l=d;break a}!h&&m&&p(m,f)&&
(h=p(m,f),n=d)}!e&&h&&(e=h,l=n);e&&(k.splice(0,l,e),a=k.join("/"))}return(e=p(q.pkgs,a))?e:a}function f(a){E&&y(document.getElementsByTagName("script"),function(g){if(g.getAttribute("data-requiremodule")===a&&g.getAttribute("data-requirecontext")===l.contextName)return g.parentNode.removeChild(g),!0})}function m(a){var g=p(q.paths,a);if(g&&L(g)&&1<g.length)return g.shift(),l.require.undef(a),l.makeRequire(null,{skipMap:!0})([a]),!0}function n(a){var g,d=a?a.indexOf("!"):-1;-1<d&&(g=a.substring(0,
d),a=a.substring(d+1,a.length));return[g,a]}function r(a,g,d,e){var k,b,f=null,h=g?g.name:null,q=a,r=!0,m="";a||(r=!1,a="_@r"+(R+=1));a=n(a);f=a[0];a=a[1];f&&(f=c(f,h,e),b=p(v,f));a&&(f?m=b&&b.normalize?b.normalize(a,function(a){return c(a,h,e)}):-1===a.indexOf("!")?c(a,h,e):a:(m=c(a,h,e),a=n(m),f=a[0],m=a[1],d=!0,k=l.nameToUrl(m)));d=!f||b||d?"":"_unnormalized"+(V+=1);return{prefix:f,name:m,parentMap:g,unnormalized:!!d,url:k,originalName:q,isDefine:r,id:(f?f+"!"+m:m)+d}}function u(a){var g=a.id,
b=p(t,g);b||(b=t[g]=new l.Module(a));return b}function w(a,b,d){var e=a.id,k=p(t,e);if(!x(v,e)||k&&!k.defineEmitComplete)if(k=u(a),k.error&&"error"===b)d(k.error);else k.on(b,d);else"defined"===b&&d(v[e])}function A(a,b){var g=a.requireModules,e=!1;if(b)b(a);else if(y(g,function(b){if(b=p(t,b))b.error=a,b.events.error&&(e=!0,b.emit("error",a))}),!e)h.onError(a)}function B(){T.length&&(y(T,function(a){var b=a[0];"string"===typeof b&&(l.defQueueMap[b]=!0);G.push(a)}),T=[])}function C(a){delete t[a];
delete Z[a]}function J(a,b,d){var e=a.map.id;a.error?a.emit("error",a.error):(b[e]=!0,y(a.depMaps,function(e,g){e=e.id;var k=p(t,e);!k||a.depMatched[g]||d[e]||(p(b,e)?(a.defineDep(g,v[e]),a.check()):J(k,b,d))}),d[e]=!0)}function H(){var a,b,d=(a=1E3*q.waitSeconds)&&l.startTime+a<(new Date).getTime(),e=[],k=[],c=!1,h=!0;if(!aa){aa=!0;D(Z,function(a){var g=a.map,Y=g.id;if(a.enabled&&(g.isDefine||k.push(a),!a.error))if(!a.inited&&d)m(Y)?c=b=!0:(e.push(Y),f(Y));else if(!a.inited&&a.fetched&&g.isDefine&&
(c=!0,!g.prefix))return h=!1});if(d&&e.length)return a=F("timeout","Load timeout for modules: "+e,null,e),a.contextName=l.contextName,A(a);h&&y(k,function(a){J(a,{},{})});d&&!b||!c||!E&&!ja||ba||(ba=setTimeout(function(){ba=0;H()},50));aa=!1}}function I(a){x(v,a[0])||u(r(a[0],null,!0)).init(a[1],a[2])}function N(a){a=a.currentTarget||a.srcElement;var b=l.onScriptLoad;a.detachEvent&&!ca?a.detachEvent("onreadystatechange",b):a.removeEventListener("load",b,!1);b=l.onScriptError;a.detachEvent&&!ca||a.removeEventListener("error",
b,!1);return{node:a,id:a&&a.getAttribute("data-requiremodule")}}function O(){var a;for(B();G.length;){a=G.shift();if(null===a[0])return A(F("mismatch","Mismatched anonymous define() module: "+a[a.length-1]));I(a)}l.defQueueMap={}}var aa,da,l,P,ba,q={waitSeconds:7,baseUrl:"./",paths:{},bundles:{},pkgs:{},shim:{},config:{}},t={},Z={},ea={},G=[],v={},U={},fa={},R=1,V=1;P={require:function(a){return a.require?a.require:a.require=l.makeRequire(a.map)},exports:function(a){a.usingExports=!0;if(a.map.isDefine)return a.exports?
v[a.map.id]=a.exports:a.exports=v[a.map.id]={}},module:function(a){return a.module?a.module:a.module={id:a.map.id,uri:a.map.url,config:function(){return p(q.config,a.map.id)||{}},exports:a.exports||(a.exports={})}}};da=function(a){this.events=p(ea,a.id)||{};this.map=a;this.shim=p(q.shim,a.id);this.depExports=[];this.depMaps=[];this.depMatched=[];this.pluginMaps={};this.depCount=0};da.prototype={init:function(a,b,d,e){e=e||{};if(!this.inited){this.factory=b;if(d)this.on("error",d);else this.events.error&&
(d=z(this,function(a){this.emit("error",a)}));this.depMaps=a&&a.slice(0);this.errback=d;this.inited=!0;this.ignore=e.ignore;e.enabled||this.enabled?this.enable():this.check()}},defineDep:function(a,b){this.depMatched[a]||(this.depMatched[a]=!0,--this.depCount,this.depExports[a]=b)},fetch:function(){if(!this.fetched){this.fetched=!0;l.startTime=(new Date).getTime();var a=this.map;if(this.shim)l.makeRequire(this.map,{enableBuildCallback:!0})(this.shim.deps||[],z(this,function(){return a.prefix?this.callPlugin():
this.load()}));else return a.prefix?this.callPlugin():this.load()}},load:function(){var a=this.map.url;U[a]||(U[a]=!0,l.load(this.map.id,a))},check:function(){if(this.enabled&&!this.enabling){var a,b,d=this.map.id;b=this.depExports;var e=this.exports,k=this.factory;if(!this.inited)x(l.defQueueMap,d)||this.fetch();else if(this.error)this.emit("error",this.error);else if(!this.defining){this.defining=!0;if(1>this.depCount&&!this.defined){if(K(k)){if(this.events.error&&this.map.isDefine||h.onError!==
ha)try{e=l.execCb(d,k,b,e)}catch(oa){a=oa}else e=l.execCb(d,k,b,e);this.map.isDefine&&void 0===e&&((b=this.module)?e=b.exports:this.usingExports&&(e=this.exports));if(a)return a.requireMap=this.map,a.requireModules=this.map.isDefine?[this.map.id]:null,a.requireType=this.map.isDefine?"define":"require",A(this.error=a)}else e=k;this.exports=e;if(this.map.isDefine&&!this.ignore&&(v[d]=e,h.onResourceLoad)){var c=[];y(this.depMaps,function(a){c.push(a.normalizedMap||a)});h.onResourceLoad(l,this.map,c)}C(d);
this.defined=!0}this.defining=!1;this.defined&&!this.defineEmitted&&(this.defineEmitted=!0,this.emit("defined",this.exports),this.defineEmitComplete=!0)}}},callPlugin:function(){var a=this.map,b=a.id,d=r(a.prefix);this.depMaps.push(d);w(d,"defined",z(this,function(e){var k,d,g=p(fa,this.map.id),f=this.map.name,n=this.map.parentMap?this.map.parentMap.name:null,m=l.makeRequire(a.parentMap,{enableBuildCallback:!0});if(this.map.unnormalized){if(e.normalize&&(f=e.normalize(f,function(a){return c(a,n,!0)})||
""),d=r(a.prefix+"!"+f,this.map.parentMap),w(d,"defined",z(this,function(a){this.map.normalizedMap=d;this.init([],function(){return a},null,{enabled:!0,ignore:!0})})),e=p(t,d.id)){this.depMaps.push(d);if(this.events.error)e.on("error",z(this,function(a){this.emit("error",a)}));e.enable()}}else g?(this.map.url=l.nameToUrl(g),this.load()):(k=z(this,function(a){this.init([],function(){return a},null,{enabled:!0})}),k.error=z(this,function(a){this.inited=!0;this.error=a;a.requireModules=[b];D(t,function(a){0===
a.map.id.indexOf(b+"_unnormalized")&&C(a.map.id)});A(a)}),k.fromText=z(this,function(e,d){var c=a.name,g=r(c),f=Q;d&&(e=d);f&&(Q=!1);u(g);x(q.config,b)&&(q.config[c]=q.config[b]);try{h.exec(e)}catch(ka){return A(F("fromtexteval","fromText eval for "+b+" failed: "+ka,ka,[b]))}f&&(Q=!0);this.depMaps.push(g);l.completeLoad(c);m([c],k)}),e.load(a.name,m,k,q))}));l.enable(d,this);this.pluginMaps[d.id]=d},enable:function(){Z[this.map.id]=this;this.enabling=this.enabled=!0;y(this.depMaps,z(this,function(a,
b){var d,e;if("string"===typeof a){a=r(a,this.map.isDefine?this.map:this.map.parentMap,!1,!this.skipMap);this.depMaps[b]=a;if(d=p(P,a.id)){this.depExports[b]=d(this);return}this.depCount+=1;w(a,"defined",z(this,function(a){this.undefed||(this.defineDep(b,a),this.check())}));this.errback?w(a,"error",z(this,this.errback)):this.events.error&&w(a,"error",z(this,function(a){this.emit("error",a)}))}d=a.id;e=t[d];x(P,d)||!e||e.enabled||l.enable(a,this)}));D(this.pluginMaps,z(this,function(a){var b=p(t,a.id);
b&&!b.enabled&&l.enable(a,this)}));this.enabling=!1;this.check()},on:function(a,b){var d=this.events[a];d||(d=this.events[a]=[]);d.push(b)},emit:function(a,b){y(this.events[a],function(a){a(b)});"error"===a&&delete this.events[a]}};l={config:q,contextName:b,registry:t,defined:v,urlFetched:U,defQueue:G,defQueueMap:{},Module:da,makeModuleMap:r,nextTick:h.nextTick,onError:A,configure:function(a){a.baseUrl&&"/"!==a.baseUrl.charAt(a.baseUrl.length-1)&&(a.baseUrl+="/");if("string"===typeof a.urlArgs){var b=
a.urlArgs;a.urlArgs=function(a,e){return(-1===e.indexOf("?")?"?":"\x26")+b}}var d=q.shim,e={paths:!0,bundles:!0,config:!0,map:!0};D(a,function(a,b){e[b]?(q[b]||(q[b]={}),X(q[b],a,!0,!0)):q[b]=a});a.bundles&&D(a.bundles,function(a,b){y(a,function(a){a!==b&&(fa[a]=b)})});a.shim&&(D(a.shim,function(a,b){L(a)&&(a={deps:a});!a.exports&&!a.init||a.exportsFn||(a.exportsFn=l.makeShimExports(a));d[b]=a}),q.shim=d);a.packages&&y(a.packages,function(a){var b;a="string"===typeof a?{name:a}:a;b=a.name;a.location&&
(q.paths[b]=a.location);q.pkgs[b]=a.name+"/"+(a.main||"main").replace(pa,"").replace(S,"")});D(t,function(a,b){a.inited||a.map.unnormalized||(a.map=r(b,null,!0))});(a.deps||a.callback)&&l.require(a.deps||[],a.callback)},makeShimExports:function(a){return function(){var b;a.init&&(b=a.init.apply(ga,arguments));return b||a.exports&&ia(a.exports)}},makeRequire:function(a,g){function d(e,c,f){var k,m;g.enableBuildCallback&&c&&K(c)&&(c.__requireJsBuild=!0);if("string"===typeof e){if(K(c))return A(F("requireargs",
"Invalid require call"),f);if(a&&x(P,e))return P[e](t[a.id]);if(h.get)return h.get(l,e,a,d);k=r(e,a,!1,!0);k=k.id;return x(v,k)?v[k]:A(F("notloaded",'Module name "'+k+'" has not been loaded yet for context: '+b+(a?"":". Use require([])")))}O();l.nextTick(function(){O();m=u(r(null,a));m.skipMap=g.skipMap;m.init(e,c,f,{enabled:!0});H()});return d}g=g||{};X(d,{isBrowser:E,toUrl:function(b){var e,d=b.lastIndexOf("."),f=b.split("/")[0];-1!==d&&("."!==f&&".."!==f||1<d)&&(e=b.substring(d,b.length),b=b.substring(0,
d));return l.nameToUrl(c(b,a&&a.id,!0),e,!0)},defined:function(b){return x(v,r(b,a,!1,!0).id)},specified:function(b){b=r(b,a,!1,!0).id;return x(v,b)||x(t,b)}});a||(d.undef=function(b){B();var d=r(b,a,!0),e=p(t,b);e.undefed=!0;f(b);delete v[b];delete U[d.url];delete ea[b];W(G,function(a,d){a[0]===b&&G.splice(d,1)});delete l.defQueueMap[b];e&&(e.events.defined&&(ea[b]=e.events),C(b))});return d},enable:function(a){p(t,a.id)&&u(a).enable()},completeLoad:function(a){var b,d,e=p(q.shim,a)||{},c=e.exports;
for(B();G.length;){d=G.shift();if(null===d[0]){d[0]=a;if(b)break;b=!0}else d[0]===a&&(b=!0);I(d)}l.defQueueMap={};d=p(t,a);if(!b&&!x(v,a)&&d&&!d.inited)if(!q.enforceDefine||c&&ia(c))I([a,e.deps||[],e.exportsFn]);else return m(a)?void 0:A(F("nodefine","No define call for "+a,null,[a]));H()},nameToUrl:function(a,b,d){var e,c,f,g;(e=p(q.pkgs,a))&&(a=e);if(e=p(fa,a))return l.nameToUrl(e,b,d);if(h.jsExtRegExp.test(a))e=a+(b||"");else{e=q.paths;c=a.split("/");for(f=c.length;0<f;--f)if(g=c.slice(0,f).join("/"),
g=p(e,g)){L(g)&&(g=g[0]);c.splice(0,f,g);break}e=c.join("/");e+=b||(/^data\:|^blob\:|\?/.test(e)||d?"":".js");e=("/"===e.charAt(0)||e.match(/^[\w\+\.\-]+:/)?"":q.baseUrl)+e}return q.urlArgs&&!/^blob\:/.test(e)?e+q.urlArgs(a,e):e},load:function(a,b){h.load(l,a,b)},execCb:function(a,b,d,c){return b.apply(c,d)},onScriptLoad:function(a){if("load"===a.type||qa.test((a.currentTarget||a.srcElement).readyState))M=null,a=N(a),l.completeLoad(a.id)},onScriptError:function(a){var b=N(a);if(!m(b.id)){var c=[];
D(t,function(a,d){0!==d.indexOf("_@r")&&y(a.depMaps,function(a){if(a.id===b.id)return c.push(d),!0})});return A(F("scripterror",'Script error for "'+b.id+(c.length?'", needed by: '+c.join(", "):'"'),a,[b.id]))}}};l.require=l.makeRequire();return l}function ra(){if(M&&"interactive"===M.readyState)return M;W(document.getElementsByTagName("script"),function(b){if("interactive"===b.readyState)return M=b});return M}var h,B,C,H,N,I,M,O,u,V,sa=/(\/\*([\s\S]*?)\*\/|([^:]|^)\/\/(.*)$)/mg,ta=/[^.]\s*require\s*\(\s*["']([^'"\s]+)["']\s*\)/g,
S=/\.js$/,pa=/^\.\//;B=Object.prototype;var R=B.toString,ma=B.hasOwnProperty,E=!("undefined"===typeof window||"undefined"===typeof navigator||!window.document),ja=!E&&"undefined"!==typeof importScripts,qa=E&&"PLAYSTATION 3"===navigator.platform?/^complete$/:/^(complete|loaded)$/,ca="undefined"!==typeof opera&&"[object Opera]"===opera.toString(),J={},w={},T=[],Q=!1;if("undefined"===typeof define){if("undefined"!==typeof requirejs){if(K(requirejs))return;w=requirejs;requirejs=void 0}"undefined"===typeof require||
K(require)||(w=require,require=void 0);h=requirejs=function(b,c,f,m){var n,r="_";L(b)||"string"===typeof b||(n=b,L(c)?(b=c,c=f,f=m):b=[]);n&&n.context&&(r=n.context);(m=p(J,r))||(m=J[r]=h.s.newContext(r));n&&m.configure(n);return m.require(b,c,f)};h.config=function(b){return h(b)};h.nextTick="undefined"!==typeof setTimeout?function(b){setTimeout(b,4)}:function(b){b()};require||(require=h);h.version="2.2.0";h.jsExtRegExp=/^\/|:|\?|\.js$/;h.isBrowser=E;B=h.s={contexts:J,newContext:na};h({});y(["toUrl",
"undef","defined","specified"],function(b){h[b]=function(){var c=J._;return c.require[b].apply(c,arguments)}});E&&(C=B.head=document.getElementsByTagName("head")[0],H=document.getElementsByTagName("base")[0])&&(C=B.head=H.parentNode);h.onError=ha;h.createNode=function(b,c,f){c=b.xhtml?document.createElementNS("http://www.w3.org/1999/xhtml","html:script"):document.createElement("script");c.type=b.scriptType||"text/javascript";c.charset="utf-8";c.async=!0;return c};h.load=function(b,c,f){var m=b&&b.config||
{},n;if(E){n=h.createNode(m,c,f);n.setAttribute("data-requirecontext",b.contextName);n.setAttribute("data-requiremodule",c);!n.attachEvent||n.attachEvent.toString&&0>n.attachEvent.toString().indexOf("[native code")||ca?(n.addEventListener("load",b.onScriptLoad,!1),n.addEventListener("error",b.onScriptError,!1)):(Q=!0,n.attachEvent("onreadystatechange",b.onScriptLoad));n.src=f;if(m.onNodeCreated)m.onNodeCreated(n,m,c,f);O=n;H?C.insertBefore(n,H):C.appendChild(n);O=null;return n}if(ja)try{setTimeout(function(){},
0),importScripts(f),b.completeLoad(c)}catch(r){b.onError(F("importscripts","importScripts failed for "+c+" at "+f,r,[c]))}};E&&!w.skipDataMain&&W(document.getElementsByTagName("script"),function(b){C||(C=b.parentNode);if(N=b.getAttribute("data-main"))return u=N,w.baseUrl||-1!==u.indexOf("!")||(I=u.split("/"),u=I.pop(),V=I.length?I.join("/")+"/":"./",w.baseUrl=V),u=u.replace(S,""),h.jsExtRegExp.test(u)&&(u=N),w.deps=w.deps?w.deps.concat(u):[u],!0});define=function(b,c,f){var h,n;"string"!==typeof b&&
(f=c,c=b,b=null);L(c)||(f=c,c=null);!c&&K(f)&&(c=[],f.length&&(f.toString().replace(sa,la).replace(ta,function(b,f){c.push(f)}),c=(1===f.length?["require"]:["require","exports","module"]).concat(c)));Q&&(h=O||ra())&&(b||(b=h.getAttribute("data-requiremodule")),n=J[h.getAttribute("data-requirecontext")]);n?(n.defQueue.push([b,c,f]),n.defQueueMap[b]=!0):T.push([b,c,f])};define.amd={jQuery:!0};h.exec=function(b){return eval(b)};h(w)}})(this);